version: '3.9'

services:

  apifinciclo:
    container_name:  hltb_microservice_container
    image: hltb_microservice:latest
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - 5000:8910
    env_file:
      - .env